name             'dev'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures dev'
long_description 'Installs/Configures dev'
version          '0.1.0'
