name             'sensors'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures sensors'
long_description 'Installs/Configures sensors'
version          '0.1.0'
