name             'wiringpi'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures wiringpi'
long_description 'Installs/Configures wiringpi'
version          '0.1.0'
